import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';

import './globals.css';
import Providers from './providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  manifest: `${process.env.NEXT_PUBLIC_BASE_PATH}/manifest.json`,
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="96x96" href={`${process.env.NEXT_PUBLIC_BASE_PATH}/icons/icon-96x96.png`} />
        <link rel="apple-touch-icon" sizes="120x120" href={`${process.env.NEXT_PUBLIC_BASE_PATH}/icons/icon-120x120.png`} />
        <link rel="apple-touch-icon" sizes="152x152" href={`${process.env.NEXT_PUBLIC_BASE_PATH}/icons/icon-152x152.png`} />
        <link rel="apple-touch-icon" sizes="180x180" href={`${process.env.NEXT_PUBLIC_BASE_PATH}/icons/icon-180x180.png`} />
        <link rel="icon" type="image/png" sizes="192x192" href={`${process.env.NEXT_PUBLIC_BASE_PATH}/icons/icon-192x192.png`} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
